name: vlab
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pytorch>=2.2.1
  - torchvision
  - pytorch-cuda=11.8  # Change to 11.8 if your system doesb't uses CUDA 12.1
  - pip
  - pip:
      - transformers>=4.50.3
      - accelerate>=1.7.0
      - datasets>=2.19.0
      - av>=14.2.0
      - safetensors>=0.4.3
      - draccus==0.10.0
      - "huggingface-hub[hf-transfer,cli]>=0.27.1"
      - termcolor>=2.4.0
      - einops>=0.8.0
      - "imageio[ffmpeg]>=2.34.0"
      - jsonlines>=4.0.0
      - deepdiff>=7.0.1
      - packaging>=24.2
      - wandb>=0.16.3
      - trackio>=0.7.0

